// weena.af login
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

// facebook login
const FB_LOGIN_REQUEST = "FB_LOGIN_REQUEST";
const FB_LOGIN_SUCCESS = "FB_LOGIN_SUCCESS";
const FB_LOGIN_FAILURE = "FB_LOGIN_FAILURE";

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  FB_LOGIN_FAILURE,
  FB_LOGIN_REQUEST,
  FB_LOGIN_SUCCESS
};
