const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILURE = "SIGNUP_FAILURE";
const SIGNUP_EMAIL = "SIGNUP_EMAIL";
const SIGNUP_FULL_NAME = "SIGNUP_FULL_NAME";
const SIGNUP_VERIFY_REQUEST = "SIGNUP_VERIFY_REQUEST";
const SIGNUP_VERIFY_SUCCESS = "SIGNUP_VERIFY_SUCCESS";
const SIGNUP_VERIFY_FAILURE = "SIGNUP_VERIFY_FAILURE";

export {
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILURE,
  SIGNUP_EMAIL,
  SIGNUP_FULL_NAME,
  SIGNUP_VERIFY_REQUEST,
  SIGNUP_VERIFY_SUCCESS,
  SIGNUP_VERIFY_FAILURE
};
