const PROFILE_CHANGE_REQUEST = "PROFILE_CHANGE_REQUEST";
const PROFILE_CHANGE_SUCCESS = "PROFILE_CHANGE_SUCCESS";
const PROFILE_CHANGE_FAILURE = "PROFILE_CHANGE_FAILURE";

const ADD_NEW_STORY_BUTTON_CONDITION = "ADD_NEW_STORY_BUTTON_CONDITION";
const ADD_NEW_STORY_BUTTON_PRESSED = "ADD_NEW_STORY_BUTTON_PRESSED";

export {
  PROFILE_CHANGE_FAILURE,
  PROFILE_CHANGE_REQUEST,
  PROFILE_CHANGE_SUCCESS,
  ADD_NEW_STORY_BUTTON_CONDITION,
  ADD_NEW_STORY_BUTTON_PRESSED
};
