const PROFILE_CHANGE_REQUEST = "PROFILE_CHANGE_REQUEST";
const PROFILE_CHANGE_SUCCESS = "PROFILE_CHANGE_SUCCESS";
const PROFILE_CHANGE_FAILURE = "PROFILE_CHANGE_FAILURE";

export {
  PROFILE_CHANGE_FAILURE,
  PROFILE_CHANGE_REQUEST,
  PROFILE_CHANGE_SUCCESS
};
